# Generated by Django 4.1.7 on 2023-04-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cust",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_desc", models.TextField(max_length=2000)),
                ("post_image_link", models.CharField(max_length=500)),
                ("post_date", models.DateTimeField(auto_now_add=True)),
                ("post_likes", models.IntegerField(default=0)),
                ("post_user_name", models.CharField(max_length=100, null=True)),
                ("post_likes_user", models.ManyToManyField(to="like_comment.cust")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_text", models.CharField(max_length=1000)),
                (
                    "comment_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="like_comment.post",
                    ),
                ),
                (
                    "comment_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="like_comment.cust",
                    ),
                ),
            ],
        ),
    ]
