version: '3'

x-environment: &env
  SERVICE_REGISTRY_TOKEN: "ABCDEFG"
  ADMIN_SERVICE_TOKEN: "a90xIy6XopQkp8WNuaOFqRrg2XB6BfAYNdPJqKuIRmM0q5jyJj"
  JWT_TOKEN_HEADER_NAME: "x-jwt-token"
  SERVICE_REGISTRY_PORT: 9000
  AUTHENTICATION_SERVICE_PORT: 8081
  ADMIN_SERVICE_PORT: 8082
  VIDEO_PROCESSING_SERVICE_PORT: 8083
  COLLECTION_ORCHESTRATION_PORT: 8084

services:
  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      <<: *env
      DATABASE_HOST_URL: "mongodb://main-user:391A0777775C663B07E6B5B7E0886D56@mongodb/auth-service"

#  video-processing-service:
#    build:
#      context: ./nodejs-app-2
#      dockerfile: Dockerfile
#    ports:
#      - "8002:8002"
#    depends_on:
#      - mongodb
#    environment: *env

  admin-management:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      <<: *env
      DATABASE_HOST_URL: "mongodb://main-user:391A0777775C663B07E6B5B7E0886D56@mongodb/admin-service"

  collection-orchestration:
    build:
        context: ./collection-orchestration
        dockerfile: Dockerfile
    ports:
        - "8084:8084"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: K9A1qfhb1pWZV186eJasTE9kgrHLMTRzaaHnSjQ8RzVNvlashE
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DB:-mongodb}
      MONGO_INITDB_DATABASE: init  # arbitrary value
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d/

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    environment: *env
