version: '3'

x-environment: &env
  SERVICE_REGISTRY_TOKEN: "ABCDEFG"
  ADMIN_SERVICE_TOKEN: "a90xIy6XopQkp8WNuaOFqRrg2XB6BfAYNdPJqKuIRmM0q5jyJj"
  SERVICE_REGISTRY_PORT: 9000
  AUTHENTICATION_SERVICE_PORT: 8081
  ADMIN_SERVICE_PORT: 8082
  VIDEO_PROCESSING_SERVICE_PORT: 8083

services:
  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      <<: *env
      DATABASE_HOST_URL: "mongodb://main-user:391A0777775C663B07E6B5B7E0886D56@mongodb/auth-service"

  video-processing-service:
    build:
      context: ./video-processor
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    environment: *env

  admin-management:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      <<: *env
      DATABASE_HOST_URL: "mongodb://main-user:391A0777775C663B07E6B5B7E0886D56@mongodb/admin-service"


  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: K9A1qfhb1pWZV186eJasTE9kgrHLMTRzaaHnSjQ8RzVNvlashE
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DB:-mongodb}
      MONGO_INITDB_DATABASE: init  # arbitrary value
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d/

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    environment: *env

  art-collection-service:
    build:
      context: ./art-collection-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    environment:
      <<: *env
      DATABASE_HOST_URL: "postgres://postgres:t9D56xfRPPqGdKids7I68O64glP5dKH4yUS5H52L2bnFMgHaHq@postgres:5432/ai-art-collections"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t9D56xfRPPqGdKids7I68O64glP5dKH4yUS5H52L2bnFMgHaHq
      POSTGRES_DB: ai-art-collections
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
