version: '3'

x-environment: &env
  SERVICE_REGISTRY_TOKEN: "ABCDEFG"
  ADMIN_SERVICE_TOKEN: "a90xIy6XopQkp8WNuaOFqRrg2XB6BfAYNdPJqKuIRmM0q5jyJj"
  JWT_TOKEN_HEADER_NAME: "x-jwt-token"
  SERVICE_REGISTRY_PORT: 9000

  FRONTEND_SERVICE_PORT: 8080
  AUTHENTICATION_SERVICE_PORT: 8081
  ADMIN_SERVICE_PORT: 8082
  VIDEO_PROCESSING_SERVICE_PORT: 8083
  COLLECTION_INTERACTIONS_ORCHESTRATION_PORT: 8084
  LOGIN_ORCHESTRATION_PORT: 8085
  # ART_COLLECTIONS_PORT: 8086
  # LIKE_RATING_SERVICE_PORT: 8087
#  SERVICE_REGISTRY_URL: "http://service-registry:9000"
  FRONTEND_SERVICE_URL: "http://frontend-service:8080"
  AUTHENTICATION_SERVICE_URL: "http://authentication-service:8081"
  ADMIN_SERVICE_URL: "http://admin-service:8082"
  VIDEO_PROCESSING_SERVICE_URL: "http://video-processing-service:8083"
  COLLECTION_ORCHESTRATION_URL: "http://collection-orchestration:8084"
  LOGIN_ORCHESTRATION_URL: "http://login-orchestration:8085"
  # ART_COLLECTIONS_URL: "http://art-collections:8086"
  # LIKE_RATING_SERVICE_URL: "http://like-rating-service:8087"


services:
  frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      <<: *env
    volumes:
      - "./frontend:/code-frontend-service"
      - "/code-frontend-service/node_modules"


#  eureka-server:
#    image: springcloud/eureka
#    ports:
#      - "8761:8761"
#    environment:
#      - JAVA_OPTS=-Xmx512m


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      <<: *env
      DATABASE_HOST_URL: "mongodb://main-user:391A0777775C663B07E6B5B7E0886D56@mongodb/auth-service"

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      <<: *env
      DATABASE_HOST_URL: "mongodb://main-user:391A0777775C663B07E6B5B7E0886D56@mongodb/admin-service"

  video-processing-service:
    build:
      context: ./video-processor
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    environment: *env

  collection-interactions-orchestration:
    build:
        context: ./collection-interactions-orchestration
        dockerfile: Dockerfile
    ports:
        - "8084:8084"
    depends_on:
      - admin-service
      - login-orchestration
#      - art-collections
#      - like-rating-service
    environment:
      <<: *env

  login-orchestration:
    build:
      context: ./login-orchestration
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - authentication-service
      - admin-service
    environment:
      <<: *env
      JWT_SECRET_KEY: "jv3Vh7b0upzBgZ8ocoOASSTjk0ypkBxO6NHqA5RIHFWEN5U5Vd"
    volumes:
      - "./login-orchestration:/code-login-orchestration"
      - "/code-login-orchestration/node_modules"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: K9A1qfhb1pWZV186eJasTE9kgrHLMTRzaaHnSjQ8RzVNvlashE
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DB:-mongodb}
      MONGO_INITDB_DATABASE: init  # arbitrary value
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d/

  art-collection-service:
    build:
      context: ./art-collection-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    volumes:
      - "./art-collection-service/pip-cache:/pip-cache"
    environment:
      <<: *env
      DATABASE_HOST_URL: "postgres://postgres:t9D56xfRPPqGdKids7I68O64glP5dKH4yUS5H52L2bnFMgHaHq@postgres:5432/ai-art-collections"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t9D56xfRPPqGdKids7I68O64glP5dKH4yUS5H52L2bnFMgHaHq
      POSTGRES_DB: ai-art-collections
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t9D56xfRPPqGdKids7I68O64glP5dKH4yUS5H52L2bnFMgHaHq
      POSTGRES_DB: like-and-comment
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
