# Generated by Django 4.1.7 on 2023-05-21 05:52

from django.db import migrations, models

import export_collections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=500)),
                ('collection_owner', models.CharField(max_length=500)),
                ('collection_images', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('video_processing_url', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('exp_date', models.DateTimeField(db_index=True)),
                ('export_instance_id', models.IntegerField(default=export_collections.models.get_export_collection_instance_id)),
            ],
        ),
    ]
