# Generated by Django 4.1.7 on 2023-05-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_comment', '0002_alter_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('username', 'collection'), name='unique_migration_host_combination'),
        ),
    ]
