swagger: "2.0"
info:
  version: "1.0.0"
  title: "Example API"
  description: "An example API for demonstrating Swagger"
host: localhost:8081
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/{id}:
    get:
      summary: Get user by ID
      description: Returns a user object by its ID.
      parameters:
        - name: id
          in: path
          description: ID of the user to retrieve
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/User"
        404:
          description: User not found
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      email:
        type: string
        format: email
    required:
      - id
      - name
