version: '3'


services:
  eureka-server:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    environment:
      EUREKA_SERVER_PORT: 8761
      JAVA_OPTS: "-Xmx512m -Xms256m"
    volumes:
      - "./eureka-server:/eureka-server"
